--q3
USE DESTINATION1868;
DROP TABLE IF EXISTS ACTOR;
CREATE TABLE ACTOR (
    ACTORID INT PRIMARY KEY,
    FIRSTNAME VARCHAR(100),
    SURNAME VARCHAR(100),
    GENDER VARCHAR(1),
    DATEOFBIRTH DATE,
    BIRTHCOUNTRY VARCHAR(50)

)
--q4
DROP TABLE IF EXISTS ERROR_EVENT1868;
CREATE TABLE ERROR_EVENT1868 (
    ERRORID INT IDENTITY(1,1) PRIMARY KEY,
    SOURCEDB NVARCHAR(100) NOT NULL,
    SOURCETABLE NVARCHAR(100) NOT NULL,
    SOURCEPKCOL NVARCHAR(100) NOT NULL,
    SOURCEPK NVARCHAR(100) NOT NULL,
    FILTERID INT NOT NULL,
    ACTION NVARCHAR(100) NOT NULL,
);

CREATE TABLE COUNTRY_SPELLING1868 (
    INVALID NVARCHAR(100),
    VALID NVARCHAR(100) NOT NULL,
);

INSERT INTO COUNTRY_SPELLING1868 (INVALID,VALID)
VALUES  ('UAS','USA'),
('United States','USA'),
('United States of America','USA'),
('Unyted Staytes','USA'),
('United Staytes','USA'),
('Aussie','Australia'),
('Straya','Australia'),
('OZ','Australia'),
('Down Under','Australia'),
('Kiwi Land','New Zealand');

--q5
SELECT *
FROM OPENROWSET('SQLNCLI', 'Server=ddc.cmetqswvqooi.us-west-1.rds.amazonaws.com;UID=admin;PWD=Dayezobel*70;',
'SELECT * FROM ETL_SOURCE.dbo.actor');

-- Question 6.
SELECT *
FROM OPENROWSET('SQLNCLI', 'Server=ddc.cmetqswvqooi.us-west-1.rds.amazonaws.com;UID=admin;PWD=Dayezobel*70;',
'SELECT * FROM ETL_SOURCE.dbo.actor')
WHERE BIRTHCOUNTRY IN (SELECT CS.INVALID FROM COUNTRY_SPELLING1868 CS WHERE BIRTHCOUNTRY = INVALID);